name: Run automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: all_tests
        type: choice
        options:
          - all_tests
          - smoke_tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run all tests
        if: ${{ github.event.inputs.deployment_target == 'all_tests' }}
        run: pytest --tracing=retain-on-failure --alluredir=allure-results

      - name: Run smoke tests
        if: ${{ github.event.inputs.deployment_target == 'smoke_tests' }}
        run: pytest -m smoke --alluredir=allure-results

      - name: Upload allure-results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-and-publish-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -sf /opt/allure-2.27.0/bin/allure /usr/local/bin/allure

      - name: Download allure-results artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure HTML report
        run: allure generate allure-results -o allure-report --clean

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
