name: Run automated tests and publish Allure report

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: all_tests
        type: choice
        options:
          - all_tests
          - smoke_tests

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run all tests
        if: ${{ github.event.inputs.deployment_target == 'all_tests' }}
        run: pytest --tracing=retain-on-failure --alluredir=allure-results

      - name: Run smoke tests
        if: ${{ github.event.inputs.deployment_target == 'smoke_tests' }}
        run: pytest -m smoke --alluredir=allure-results

      - name: Upload allure-results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate run report
    steps:
      - name: Download allure-results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
  
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
  
      - name: Install Allure CLI
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          sudo tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure
  
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report
  
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: 'true'
